package com.example.scorecheckingapp.API.NewsApi

data class ArticleX(
    val additionalCategories: List<Any>,
    val authors: List<AuthorX>,
    val body: List<BodyX>,
    val category: CategoryXXX,
    val categoryLabel: String,
    val channels: List<Any>,
    val createdAt: String,
    val entityType: String,
    val id: String,
    val isAdsEnabled: Boolean,
    val isAdultContent: Boolean,
    val isArticleAvailable: Boolean,
    val isLive: Boolean,
    val isSensitiveContent: Boolean,
    val leagues: List<League>,
    val mainMedia: MainMediaXXXX,
    val origin: Any,
    val provider: String,
    val publishedAt: String,
    val publishedBy: PublishedBy,
    val publishedDate: String,
    val publishedRegions: List<Any>,
    val publishedTime: String,
    val related: RelatedX,
    val seo: SeoXXXXXXX,
    val status: String,
    val subTitle: Any,
    val teams: List<Team>,
    val title: String,
    val type: Any,
    val until: Any,
    val updatedAt: UpdatedAtXX,
    val updatedAtUtc: String,
    val url: String
)