package com.example.scorecheckingapp.API.NewsApi

data class Data(
    val additional_categories: List<AdditionalCategory>,
    val adult_content: Boolean,
    val authors: List<Author>,
    val betting_content: Boolean,
    val body: List<Body>,
    val category: CategoryXX,
    val comments: Comments,
    val created_at: String,
    val created_by: CreatedByXXXXX,
    val custom_author: String,
    val entity_type: String,
    val footer: Any,
    val generic: Any,
    val id: String,
    val image: Image,
    val important: Boolean,
    val language: String,
    val live: Boolean,
    val main_media: List<MainMediaXXX>,
    val origin: Any,
    val published_at: String,
    val published_channels: List<Any>,
    val published_regions: List<Any>,
    val published_until: Any,
    val run_ads: Boolean,
    val sensitive_content: Boolean,
    val seo: SeoXXXXX,
    val status: String,
    val strapline: Any,
    val subtitle: Any,
    val title: String,
    val type: Any,
    val updated_at: String,
    val urls: UrlsXXXX
)