package com.example.scorecheckingapp.API.favouriteApi

data class favourite(
    val EO: Int,
    val Eact: Int,
    val Ecov: Int,
    val Edf: Long,
    val Eds: Long,
    val Ehid: Int,
    val Eid: String,
    val Eloff: Int,
    val Epr: Int,
    val Eps: String,
    val Ern: Int,
    val ErnInf: String,
    val Esd: Long,
    val Esid: Int,
    val Et: Int,
    val Ewt: Int,
    val Incs_s: IncsS,
    val LuC: Int,
    val LuUT: Long,
    val Media: Media,
    val Pid: Int,
    val Pids: Pids,
    val Sids: Sids,
    val Spid: Int,
    val Stg: Stg,
    val T1: List<T1>,
    val T2: List<T2>,
    val Tr1: String,
    val Tr1OR: String,
    val Tr2: String,
    val Tr2OR: String,
    val Trh1: String,
    val Trh2: String
)